version: '3.8'

services:
  api:
    build:
      context: ./backend
    container_name: filament-api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - UVICORN_RELOAD=True
    depends_on:
      - mssql
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  frontend-flask:
    build:
      context: ./frontend
      dockerfile: Dockerfile.flask
    container_name: frontend-flask
    expose:
      - "5000"

  frontend-nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile.nginx
    container_name: frontend-nginx
    ports:
      - "80:80"
    depends_on:
      - frontend-flask
volumes:
  mssql_data: